language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
env:
  global:
    - PINS="arp.1.0.0:. arp-mirage.1.0.0:."
    - EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git#arp"
    - TESTS=true
  matrix:
    - OCAML_VERSION=4.04 PACKAGE="arp-mirage"
    - OCAML_VERSION=4.05 PACKAGE="arp"
    - OCAML_VERSION=4.06 PACKAGE="arp-mirage"
    - OCAML_VERSION=4.07 PACKAGE="arp"
notifications:
  email: false
